- hosts: all
  become: true
  vars:
    repo_url: "https://github.com/AleXAnastasov77/simple-webapp.git"
    app_root: /opt/simple-webapp/app
    repo_dest: /opt/simple-webapp
    node_exporter_version: "1.8.1"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - git
          - python3
          - python3-pip
          - python3-dev
          - build-essential
          - libmysqlclient-dev
        state: present

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: HEAD
        force: yes

    - name: Install Python requirements
      pip:
        requirements: "{{ app_root }}/requirements.txt"
        executable: pip3

    # ---------------------------
    # Prometheus Node Exporter
    # ---------------------------
    - name: Download Node Exporter tarball
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=nobody
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Enable and start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    # ---------------------------
    # Web App systemd service
    # ---------------------------
    - name: Create systemd service for webapp
      copy:
        dest: /etc/systemd/system/webapp.service
        content: |
          [Unit]
          Description=Simple WebApp
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory={{ app_root }}
          ExecStart=/usr/bin/python3 app.py
          Restart=always
          EnvironmentFile=/etc/webapp.env

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd to pick up new service
      command: systemctl daemon-reload

    - name: Enable and start webapp service
      systemd:
        name: webapp
        enabled: yes
        state: stopped
