name: Packer Build AMI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "packer/**"
      - "app/**"
permissions:
  id-token: write
  contents: read

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::057827529833:role/GitHubActionsPipeline
          aws-region: eu-central-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: 1.11.2

      - name: Init Packer
        working-directory: ./packer
        run: packer init webserver.pkr.hcl

      - name: Build AMI with Packer + Ansible
        working-directory: ./packer
        run: packer build webserver.pkr.hcl

      - name: Extract AMI ID
        id: ami
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' ./packer/manifest.json | cut -d':' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "Built AMI: $AMI_ID"

      - name: Store AMI ID in SSM
        run: |
          aws ssm put-parameter \
            --name "/cs1/webserver/ami" \
            --value "$AMI_ID" \
            --type String \
            --overwrite
